# Generated by Django 4.1.5 on 2023-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_id',
            field=models.IntegerField(),
        ),
    ]
